<?php
$paginator = $this->paginator; ?>
<div class="panel panel-default">
    <div class="panel-heading">Отправленные письма</div>
    <div class="panel-body">
    
<div class="container-fluid">
    <div class="row">
        <div class="col-md-5">
            <a href="/email/new" class="btn btn-primary btn-xs" role="button">Написать письмо</a>
            <button type="button" class="btn btn-danger btn-xs btn-letter-delete">Удалить</button>
        </div>
    </div>
</div>
<!--  -->
<div id="table-box">
<table class="table table-striped table-hover" data-items-count="<?php echo $paginator->getTotalItemCount(); ?>">
    <thead>
        <tr>
            <th></th>
            <th>Получатель</th>
            <th>Тема</th>
            <th>Дата
                <button type="button" class="btn btn-default btn-xs date-order" style="margin-left: 10px;">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                </button>
            </th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($paginator as $item): ?>
    <tr>
        <td class="col-md-1 text-center">
            <input type="checkbox" name="<?php echo $item->getId(); ?>" class="sent-checkbox" />
        </td>
        <td class="col-md-4">
            <a href="#" class="letter-recipient"><?php echo $item->getRecipient(); ?></a>
        </td>
        <td class="col-md-4">
            <a href="/email/view/<?php echo $item->getId(); ?>" data-letter-subject>
                <?php echo $item->getSubject(); ?>
            </a>
        </td>
        <td class="col-md-3">
            <a href="#" data-sent-date="<?php echo $item->getDate()->format('Y-m-d'); ?>">
                <?php echo $item->getDate()->format('Y-m-d H:i'); ?>
            </a>
        </td>
    </tr>
<?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" style="text-align: center;">
                <?php echo $this->paginationControl($this->paginator, 'Sliding',
                    'avd-email/email/pagination'); ?>
            </td>
        </tr>
    </tfoot>
</table>
</div><!-- /.table-box -->
<!--  -->

    </div><!-- /.panel-body -->
</div><!-- /.panel panel-default  -->
<script>    
var countBadge = $('<span class="badge pull-right">').html($('[data-items-count]').attr('data-items-count'));
$('a[href="/email/sent"]').append(countBadge);

var queryObject = {
    orderBy: 'DESC',
    recipient: new String(),
    date: null,
    deleteId: null,
    paginatorPage: 1,
};

var tableBox = $("#table-box");

$(tableBox).on('click', ".sent-checkbox", function(e) {
    $(e.target).parent().parent().toggleClass('warning');
});

$(tableBox).on('click', ".date-order", function() {
    queryObject.orderBy = (queryObject.orderBy == 'DESC') ? 'ASC' : 'DESC';
    queryObject.paginatorPage = 1;
    $(tableBox).load('/email/sent table', queryObject, function(data) {
    });
});

$(tableBox).on('click', ".letter-recipient", function(e) {
    queryObject.recipient = $(e.target).html();
    queryObject.date = null;
    queryObject.paginatorPage = 1;
    $(tableBox).load('/email/sent table', queryObject, function(data) {
        $(countBadge).html($('[data-items-count]').attr('data-items-count'));
    });
    return false;
});

$(tableBox).on('click', ".paginationControl a", function(e) {
    queryObject.paginatorPage = $(this).attr('href').trim();
    $(tableBox).load("/email/sent table", queryObject, function() {
    });
    return false;
});

$(tableBox).on('click', "[data-sent-date]", function(e) {
    e.preventDefault();
    queryObject.date = $(this).attr('data-sent-date');
    queryObject.recipient = null;
    queryObject.paginatorPage = 1;
    $(tableBox).load("/email/sent table", queryObject, function(data, status, xhr) {
        $(countBadge).html($('[data-items-count]').attr('data-items-count'));
    });
});

$(tableBox).on('click', "[data-letter-subject]", function(e) {
    e.preventDefault();
    $.get($(this).attr('href'), function(data) {
        $('#letterViewModal').find('.modal-body').html(data);
        $('#letterViewModal').modal();
    });
});

$(".btn-letter-delete").on('click', function(e) {
    var queryString = new Array();
    $(".sent-checkbox").each(function() {
        if ($(this).prop('checked')) {
            queryString.push($(this).attr('name'));
        }
    });
    if (queryString.length != 0) {
        queryObject.deleteId = queryString;
        queryObject.paginatorPage = parseInt($('li[class="active"] > span').html());
        $(tableBox).load("/email/delete table", queryObject, function(data) {
            $(countBadge).html($('[data-items-count]').attr('data-items-count'));
        });
    }
});

</script>

<!-- Modal -->
<div class="modal fade" id="letterViewModal" tabindex="-1" role="dialog" aria-labelledby="letterViewModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>